services:
  api:
    build: .
    command: ["/app/api"]
    env_file:
      - .env
    environment:
      - REDIS_ADDR=redis:6379
      - DATABASE_URL=postgresql://postgres:hehe@db:5432/mydb
    depends_on:
      - redis
      - db
    ports:
      - "3000:3000"
    networks:
      - app-net

  worker:
    build: .
    env_file:
      - .env
    environment:
      - REDIS_ADDR=redis:6379
      - DATABASE_URL=postgresql://postgres:hehe@db:5432/mydb
    depends_on:
      - redis
    networks:
      - app-net
    command: ["/app/worker"]

  redis:
    image: valkey/valkey:7.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-net

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hehe
      POSTGRES_DB: mydb
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
