services:
  api:
    build: .
    command: ["/app/api"]
    env_file:
      - .env
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    ports:
      - "3000:3000"
    networks:
      - app-net

  worker:
    build: .
    env_file:
      - .env
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    networks:
      - app-net
    command: ["/app/worker"]

  redis:
    image: valkey/valkey:7.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
